[package]
name = "mpv-handler"
version = "0.1.0"
edition = "2021"
authors = ["kosette"]
description = "play videos from website using mpv"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
serde = {version = "1.0",features = ["derive"]}
thiserror = "1.0"
toml = "0.8"
