[package]
name = "mpv-handler"
version = "0.1.0"
edition = "2021"
authors = ["kosette"]
description = "play videos from website using mpv"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
regex = "1.10.3"
reqwest = {version="0.11.27",features=["json","blocking"]}
serde = {version = "1.0",features = ["derive"]}
serde_json = "1.0.114"
thiserror = "1.0"
toml = "0.8"
