[package]
name = "mpv-handler"
version = "0.2.0"
edition = "2021"
authors = ["kosette"]
description = "play videos from website using mpv"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
regex = "1.10.3"
reqwest = { version = "0.12.0", features = ["json", "blocking", "socks"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
toml = "0.8.12"
