name: CI testing
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build-release:
    permissions:
      contents: write
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        include:
          - arch: x86_64-linux-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: mpv-handler

          - arch: x86_64-windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: mpv-handler.exe

          - arch: x86_64-macos
            os: macos-latest
            target: x86_64-apple-darwin
            artifact: mpv-handler

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{matrix.target}}
        if: ${{ (!startsWith(github.ref, 'refs/tags/')) && (matrix.target != 'x86_64-pc-windows-msvc') }}
        timeout-minutes: 120
        run: |
          mkdir artifacts/
          cargo build --release --locked
          mv target/release/${{matrix.artifact}} artifacts/mpv-handler-${{matrix.arch}}
          mv *.md scripts/config.toml.template LICENSE artifacts/
          tar -czf mpv-handler-${{matrix.arch}}.tar.gz artifacts/*

      - name: Build ${{matrix.target}}
        if: ${{ (!startsWith(github.ref, 'refs/tags/')) && (matrix.target == 'x86_64-pc-windows-msvc') }}
        run: |
          cargo build --release --locked
          cargo build -p handler-config --release --locked
          mkdir artifacts/
          mv target/release/${{matrix.artifact}} artifacts/
          mv target/release/handler-config.exe artifacts/
          mv scripts/config.toml.template artifacts/
          mv *.md artifacts/
          mv LICENSE artifacts/
          compress-archive -path artifacts/* -destination artifacts/mpv-handler-${{matrix.arch}}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mpv-handler-${{matrix.arch}}
          path: |
            artifacts/*.zip
            ./*.tar.gz
          compression-level: 5
          retention-days: 3

